# https://chatgpt.com/share/6786d7a7-1a50-8010-99ed-ef1022ac1d70

services:
  app:
    
    build:
      context: .
      dockerfile: Dockerfile
    
    ports: 
      - "3000:3000"

    depends_on: db

    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bdms


  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: 
      - MYSQL_DATABASE: bdms
    volumes:
      - db_data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     PMA_HOST: db  
  #     MYSQL_ROOT_PASSWORD: yourpassword
  #   ports:
  #     - "8080:80"  # via localhost:8080

  volumes:
    db_data:


